#ifndef CONIFG_H
#define CONFIG_H
#define CONFIG_EXP_FPS 0.02F	
#define CONFIG_EXP 102
#define SHOT_MAG 2.f
#define BULLET_DELAY 0.25F

enum  Config{
	W_WIDTH=800,
	W_HEIGHT=600,
	EXP_IMG_WIDTH=1020,
	EXP_IMG_HEIGHT=600,
	EASY_LVLS=5,
	MED_LVLS=10,
	HARD_LVLS=20,
	MAX_SMALL=5,
	MAX_MED=11,
	MAX_BIG=21,
	BULLET_IMG_WIDTH=177,
	BULLET_SIZE=39
};

//chanbges this to enum class later
#endif